apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: ZGV2b3Bz    # echo -n 'devops' | base64
  mongo-root-password: ZGV2b3Bz    # echo -n 'devops' | base64
