apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.json: |
    {
      "version": "1.0.0",
      "productsApiBaseUri": "http://catalogue-service:5000",
      "recommendationBaseUri": "http://recommendation-service:8080",
      "votingBaseUri": "http://voting-service:8080"
    }
