apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
  labels:
    app: recommendation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
      - name: recommendation
        image: shahzadalikhan/recommendation:latest
        ports:
        - containerPort: 8080
