apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    app: voting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
      - name: voting
        image: shahzadalikhan/voting:latest
        ports:
        - containerPort: 8080
